# Generated by Django 3.2.6 on 2021-09-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210903_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='team',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
