# Generated by Django 3.2.6 on 2021-09-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='team',
        ),
        migrations.AddField(
            model_name='newuser',
            name='has_team',
            field=models.BooleanField(default=False),
        ),
    ]
