# Generated by Django 3.2.6 on 2021-09-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210906_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='has_team',
        ),
    ]
