# Generated by Django 3.2.6 on 2021-09-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('users', '0006_remove_newuser_has_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
