# Generated by Django 3.2.6 on 2021-09-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='decription',
            new_name='description',
        ),
    ]
